USE UNIFOOD
GO

CREATE ROLE KhachHang

GRANT SELECT, UPDATE ON NGUOIDUNG TO KhachHang
GRANT SELECT ON NHOMSANPHAM TO KhachHang
GRANT SELECT ON SANPHAM TO KhachHang
GRANT SELECT ON ANKEM TO KhachHang
GRANT SELECT ON GIOHANG TO KhachHang
GRANT SELECT, INSERT, UPDATE, DELETE ON DATHANG TO KhachHang
GRANT SELECT ON DONHANG TO KhachHang

CREATE ROLE QuanLy

GRANT SELECT, INSERT, UPDATE(MatKhau), DELETE ON NGUOIDUNG TO QuanLy
GRANT ALL ON NHOMSANPHAM TO QuanLy
GRANT ALL ON SANPHAM TO QuanLy
GRANT ALL ON ANKEM TO QuanLy
GRANT ALL ON DONVIGIAOHANG TO QuanLy
GRANT ALL ON KHOHANG TO QuanLy
GRANT SELECT, INSERT, UPDATE(MaGio), DELETE ON GIOHANG TO QuanLy
GRANT SELECT ON DATHANG TO QuanLy
GRANT ALL ON DONHANG TO QuanLy